# Generated by Django 4.2 on 2023-07-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
            ],
        ),
    ]
