# Generated by Django 4.2 on 2023-07-11 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_search', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='completion_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
