# Generated by Django 4.2 on 2023-07-14 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube_search', '0010_favoritechannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FavoriteVideo',
        ),
        migrations.AlterField(
            model_name='favoritechannel',
            name='channel_id',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AlterField(
            model_name='favoritechannel',
            name='name',
            field=models.CharField(default='non', max_length=100),
        ),
    ]
